// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6SxEOGfOMr-0WQvST-gMFWFNHFB43oUc',
    appId: '1:840836720482:web:34652b012bc01eb9f26e3b',
    messagingSenderId: '840836720482',
    projectId: 'primeiro-projeto-flutter2022',
    authDomain: 'primeiro-projeto-flutter2022.firebaseapp.com',
    storageBucket: 'primeiro-projeto-flutter2022.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJevr6OC6QaI9BbvzuGnJOxfCcymJPb48',
    appId: '1:840836720482:android:cb146e93d4d3329af26e3b',
    messagingSenderId: '840836720482',
    projectId: 'primeiro-projeto-flutter2022',
    storageBucket: 'primeiro-projeto-flutter2022.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGlyPxJ7uVkNxOclOUTnUywXLP29xO1e8',
    appId: '1:840836720482:ios:5e5cff5f3fa44edff26e3b',
    messagingSenderId: '840836720482',
    projectId: 'primeiro-projeto-flutter2022',
    storageBucket: 'primeiro-projeto-flutter2022.appspot.com',
    iosClientId: '840836720482-5tf6hkudvskukoddvev17s8jteb8qj48.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterPrimeiroApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGlyPxJ7uVkNxOclOUTnUywXLP29xO1e8',
    appId: '1:840836720482:ios:5e5cff5f3fa44edff26e3b',
    messagingSenderId: '840836720482',
    projectId: 'primeiro-projeto-flutter2022',
    storageBucket: 'primeiro-projeto-flutter2022.appspot.com',
    iosClientId: '840836720482-5tf6hkudvskukoddvev17s8jteb8qj48.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterPrimeiroApp',
  );
}
